context:
  name: s3-proxy
  version: "4.18.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - target_directory: src
    url: https://github.com/oxyno-zeta/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: a82cbd0414502bf28e54c83b487afb9a2f5256573f141fa6cce9268b012ec702

build:
  number: 0
  script:
    - if: win
      then:
        - cd src/cmd/s3-proxy
        - go build -o %LIBRARY_BIN%\s3-proxy.exe || exit 1
        - go-licenses save . --ignore github.com/go-chi/httptracer --save_path ..\..\..\library_licenses || exit 1
      else:
        - cd src/cmd/s3-proxy
        - go build -o $PREFIX/bin/s3-proxy
        - go-licenses save . --ignore github.com/go-chi/httptracer --save_path ../../../library_licenses

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - ${{ stdlib("c") }}
    - go-licenses

tests:
  - script:
      - s3-proxy --help

about:
  homepage: https://github.com/oxyno-zeta/s3-proxy
  summary: S3 Reverse Proxy with GET, PUT and DELETE methods and authentication (OpenID Connect and Basic Auth)
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - LICENSE-go-chi-httptracer
    # https://github.com/prefix-dev/rattler-build/issues/1443
    - library_licenses/**/*

extra:
  recipe-maintainers:
    - pavelzw
